# Generated by Django 4.2.7 on 2024-01-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knittingstore', '0002_cart_order_orderitem_order_products_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
